---
title: "Viridis Color Schemes"
author: "Andy Grogan-Kaylor"
date: "`r Sys.Date()`"
output:
  distill::distill_article:
    highlight: haddock
    toc: yes
    code_folding: true
---


```{r setup, include=FALSE}

knitr::opts_chunk$set(echo = TRUE)

```

# Viridis

The Viridis color palettes are designed to have a number of advantages.

1. Aesthetically pleasing
2. Perceptually uniform
3. Color-blind friendly

More details can be found at [https://cran.r-project.org/web/packages/viridis/vignettes/intro-to-viridis.html](https://cran.r-project.org/web/packages/viridis/vignettes/intro-to-viridis.html)

```{r}

x <- seq(1,10)

mydata <- data.frame(x)

library(ggplot2)

p1 <- ggplot(mydata,
       aes(x = x, 
           fill = factor(x),
           y = 1)) + 
  geom_col() + 
  scale_x_continuous(breaks=seq(1,10,1)) +
  theme_minimal() +
  theme(axis.text.y = element_blank(),
        axis.ticks.y = element_blank(),
        axis.title.y = element_blank())


```


## Viridis

```{r}

p1 + 
  labs(title = "Viridis") +
  scale_fill_viridis_d(name = "Viridis")

```
## Cividis

```{r}

p1 + 
  labs(title = "Cividis") +
  scale_fill_viridis_d(name = "Cividis",
                       option = "cividis")

```
## Plasma

```{r}

p1 + 
  labs(title = "Plasma") +
  scale_fill_viridis_d(name = "Plasma",
                       option = "plasma")

```

## Magma

```{r}

p1 + 
  labs(title = "Magma") +
  scale_fill_viridis_d(name = "Magma",
                       option = "magma")

```